/**
 * Extra mockup views for each merch product, by variant colour. Generated by
 * `npm run merch:mockups` — change the products in Printful and re-run it rather than
 * editing this file by hand.
 */
export const MERCH_EXTRA_MOCKUPS: Record<string, Record<string, string[]>> = {
  "456510998": {
    "Black Heather": [
      "/images/merch/456510998/black-heather-1-d37b6c65.jpg",
      "/images/merch/456510998/black-heather-2-5ef9fa1c.jpg"
    ],
    "Soft Pink": [
      "/images/merch/456510998/soft-pink-1-47d83382.jpg",
      "/images/merch/456510998/soft-pink-2-164be9cb.jpg"
    ]
  },
  "456511345": {
    "Black": [
      "/images/merch/456511345/black-1-de5c9555.jpg",
      "/images/merch/456511345/black-2-310c3fd1.jpg"
    ],
    "Navy": [
      "/images/merch/456511345/navy-1-56deab3e.jpg",
      "/images/merch/456511345/navy-2-9712a123.jpg"
    ],
    "Red": [
      "/images/merch/456511345/red-1-361e7dc7.jpg",
      "/images/merch/456511345/red-2-2d836a52.jpg"
    ],
    "Turquoise": [
      "/images/merch/456511345/turquoise-1-6c148d61.jpg",
      "/images/merch/456511345/turquoise-2-c938433a.jpg"
    ],
    "Orange": [
      "/images/merch/456511345/orange-1-43edf95e.jpg",
      "/images/merch/456511345/orange-2-ab67e91e.jpg"
    ]
  },
  "456511361": {
    "Pink": [
      "/images/merch/456511361/pink-1-1014aca3.jpg",
      "/images/merch/456511361/pink-2-d0d53145.jpg"
    ],
    "White": [
      "/images/merch/456511361/white-1-6b798133.jpg",
      "/images/merch/456511361/white-2-a5e2abab.jpg"
    ]
  },
  "456511426": {
    "Black": [
      "/images/merch/456511426/black-1-1a86e440.jpg",
      "/images/merch/456511426/black-2-7c0425dc.jpg"
    ]
  },
  "459911365": {
    "White": [
      "/images/merch/459911365/white-1-80c05f72.jpg",
      "/images/merch/459911365/white-2-d8ff7a45.jpg"
    ]
  },
  "459911463": {
    "Black": [
      "/images/merch/459911463/black-1-6fbd25cc.jpg",
      "/images/merch/459911463/black-2-eed302f8.jpg"
    ]
  },
  "459911572": {
    "Black": [
      "/images/merch/459911572/black-1-76b1d5ff.jpg",
      "/images/merch/459911572/black-2-511d7dc8.jpg"
    ]
  },
  "459911578": {
    "Black": [
      "/images/merch/459911578/black-1-c97802c8.jpg",
      "/images/merch/459911578/black-2-92b1baa8.jpg"
    ]
  },
  "459911597": {
    "Black": [
      "/images/merch/459911597/black-1-4b1ab492.jpg",
      "/images/merch/459911597/black-2-682f6075.jpg"
    ],
    "Navy": [
      "/images/merch/459911597/navy-1-343ea2d7.jpg",
      "/images/merch/459911597/navy-2-5a5b3823.jpg"
    ],
    "Red": [
      "/images/merch/459911597/red-1-907160b0.jpg",
      "/images/merch/459911597/red-2-ae1a9eed.jpg"
    ]
  }
}
