/**
 * Extra mockup views for each merch product, by variant colour. Generated by
 * `npm run merch:mockups` — change the products in Printful and re-run it rather than
 * editing this file by hand.
 */
export const MERCH_EXTRA_MOCKUPS: Record<string, Record<string, string[]>> = {
  "456510998": {
    "Black Heather": [
      "/images/merch/456510998/black-heather-1-d37b6c65.jpg",
      "/images/merch/456510998/black-heather-2-5ef9fa1c.jpg"
    ],
    "Soft Pink": [
      "/images/merch/456510998/soft-pink-1-47d83382.jpg",
      "/images/merch/456510998/soft-pink-2-164be9cb.jpg"
    ]
  },
  "456511047": {
    "White": [
      "/images/merch/456511047/white-1-5ea90765.jpg",
      "/images/merch/456511047/white-2-c46a2fcf.jpg"
    ]
  },
  "456511237": {
    "Black": [
      "/images/merch/456511237/black-1-05e9f521.jpg",
      "/images/merch/456511237/black-2-bf82c637.jpg"
    ]
  },
  "456511345": {
    "Black": [
      "/images/merch/456511345/black-1-de5c9555.jpg",
      "/images/merch/456511345/black-2-310c3fd1.jpg"
    ],
    "Navy": [
      "/images/merch/456511345/navy-1-56deab3e.jpg",
      "/images/merch/456511345/navy-2-9712a123.jpg"
    ],
    "Red": [
      "/images/merch/456511345/red-1-361e7dc7.jpg",
      "/images/merch/456511345/red-2-2d836a52.jpg"
    ],
    "Turquoise": [
      "/images/merch/456511345/turquoise-1-6c148d61.jpg",
      "/images/merch/456511345/turquoise-2-c938433a.jpg"
    ],
    "Orange": [
      "/images/merch/456511345/orange-1-43edf95e.jpg",
      "/images/merch/456511345/orange-2-ab67e91e.jpg"
    ]
  },
  "456511361": {
    "Pink": [
      "/images/merch/456511361/pink-1-1014aca3.jpg",
      "/images/merch/456511361/pink-2-d0d53145.jpg"
    ],
    "White": [
      "/images/merch/456511361/white-1-6b798133.jpg",
      "/images/merch/456511361/white-2-a5e2abab.jpg"
    ]
  },
  "456511426": {
    "Black": [
      "/images/merch/456511426/black-1-1a86e440.jpg",
      "/images/merch/456511426/black-2-7c0425dc.jpg"
    ]
  }
}
